<a href="https://colab.research.google.com/github/0ace-jk/atividades_ebac/blob/main/Mod04_Tarefa_aula_03_a_05_(base)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [280]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [281]:
# 1) Seu código aqui

# Acertos Matematica
percentual_mat = df_mat['Qt_acertos'].sum() / len(df_mat) / 24
print(f'Os alunos acertam {(percentual_mat * 100).round(2)}% das questões de Matematica')
# Acertos Portugues
percentual_por = df_por['Qt_acertos'].sum() / len(df_por) / 18
print(f'Os alunos acertam {(percentual_por * 100).round(2)}% das questões de Portugues')
# Acertos Geografia
percentual_geo = df_geo['Qt_acertos'].sum() / len(df_geo) / 8
print(f'Os alunos acertam {(percentual_geo * 100).round(2)}% das questões de Geografia')
# Acertos Ingles
percentual_ing = df_ing['Qt_acertos'].sum() / len(df_ing) / 8
print(f'Os alunos acertam {(percentual_ing * 100).round(2)}% das questões de Ingles')
# Acertos Historia
percentual_his = df_his['Qt_acertos'].sum() / len(df_his) / 8
print(f'Os alunos acertam {(percentual_his * 100).round(2)}% das questões de Historia')
# Acertos Fisica
percentual_fis = df_fis['Qt_acertos'].sum() / len(df_fis) / 12
print(f'Os alunos acertam {(percentual_fis * 100).round(2)}% das questões de Fisica')
# Acertos Quimica
percentual_qui = df_qui['Qt_acertos'].sum() / len(df_qui) / 12
print(f'Os alunos acertam {(percentual_qui * 100).round(2)}% das questões de Quimica')

Os alunos acertam 49.38% das questões de Matematica
Os alunos acertam 40.17% das questões de Portugues
Os alunos acertam 42.0% das questões de Geografia
Os alunos acertam 47.62% das questões de Ingles
Os alunos acertam 45.0% das questões de Historia
Os alunos acertam 44.33% das questões de Fisica
Os alunos acertam 45.25% das questões de Quimica

In [282]:
# aqui eu crio Data Frames específicos para cada matéria
df_mat_alunos = df_mat.rename(columns={'Qt_acertos': 'Qt_acertos_mat'})
df_por_alunos = df_por.rename(columns={'Qt_acertos': 'Qt_acertos_por'})
df_geo_alunos = df_geo.rename(columns={'Qt_acertos': 'Qt_acertos_geo'})
df_ing_alunos = df_ing.rename(columns={'Qt_acertos': 'Qt_acertos_ing'})
df_his_alunos = df_his.rename(columns={'Qt_acertos': 'Qt_acertos_his'})
df_fis_alunos = df_fis.rename(columns={'Qt_acertos': 'Qt_acertos_fis'})
df_qui_alunos = df_qui.rename(columns={'Qt_acertos': 'Qt_acertos_qui'})
df_alunos = pd.DataFrame(np.arange(1, 101),columns = ['id_aluno'])

In [283]:
# neste codigo eu concateno os dataframes das materias para um unico dataframe
# e ja indexo a coluna id_alunos
alunos = [df_alunos,
          df_mat_alunos,
          df_por_alunos,
          df_geo_alunos,
          df_ing_alunos,
          df_his_alunos,
          df_fis_alunos,
          df_qui_alunos]
df_resultado = pd.concat(alunos, axis=1)
df_resultado.set_index('id_aluno', inplace = True)

In [284]:
# 2) Seu código aqui

df_resultado['Qt_acertos_total'] = df_resultado.loc[:,'Qt_acertos_mat':].sum(axis=1)
df_resultado['Qt_acertos_total']

id_aluno
1      35
2      48
3      50
4      32
5      30
       ..
96     34
97     27
98     40
99     40
100    42
Name: Qt_acertos_total, Length: 100, dtype: int64

In [285]:
# 3) Seu código aqui

df_resultado['percentual_acertos'] = df_resultado['Qt_acertos_total'] / 90
df_resultado['percentual_acertos']

id_aluno
1      0.388889
2      0.533333
3      0.555556
4      0.355556
5      0.333333
         ...
96     0.377778
97     0.300000
98     0.444444
99     0.444444
100    0.466667
Name: percentual_acertos, Length: 100, dtype: float64

In [286]:
# 4) Seu código aqui

df_resultado['aluno_aprovado'] = df_resultado['percentual_acertos'] > 0.45
print(f"A quantidade de alunos aprovados foi de {df_resultado['aluno_aprovado'].sum()} alunos")

A quantidade de alunos aprovados foi de 47 alunos

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [298]:
# 1) seu código aqui

df_resultado['aprovado_mat'] = df_resultado['Qt_acertos_mat'] != 0
df_resultado['aprovado_fis'] = df_resultado['Qt_acertos_fis'] != 0
df_resultado['aprovado_qui'] = df_resultado['Qt_acertos_qui'] != 0
df_resultado['aluno_aprovado'] = df_resultado['aprovado_mat'] & df_resultado['aprovado_fis'] & df_resultado['aprovado_qui']
df_reprovados = df_resultado.loc[df_resultado['aluno_aprovado'] == False]
df_reprovados.head(5)

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui,Qt_acertos_total,percentual_acertos,aluno_aprovado,aprovado_mat,aprovado_fis,aprovado_qui
id_aluno,,,,,,,,,,,,,
4,10,7,3,4,0,0,8,32,0.355556,False,True,False,True
7,6,0,7,7,5,0,4,29,0.322222,False,True,False,True
11,10,8,3,2,1,7,0,31,0.344444,False,True,True,False
13,20,8,3,7,1,0,3,42,0.466667,False,True,False,True
15,7,11,1,7,1,4,0,31,0.344444,False,True,True,False

In [300]:
# 2) seu código aqui

print(f'A quantidade de alunos reprovados é de {df_reprovados.shape[0]} alunos')

A quantidade de alunos reprovados é de 23 alunos

In [306]:
# 3) seu código aqui

print(f"A média de acertos em historia desses alunos é de {df_reprovados['Qt_acertos_his'].mean().round(2)} questões")
print(f"A média de acertos em geografia desses alunos é de {df_reprovados['Qt_acertos_geo'].mean().round(2)} questões")

A média de acertos em historia desses alunos é de 3.43 questões
A média de acertos em geografia desses alunos é de 3.22 questões

In [318]:
# 4) seu código aqui

df_aprovados = df_resultado.loc[df_resultado['aluno_aprovado'] == True]
print(f'Aprovados: {df_aprovados.shape[0]} alunos')
df_aprovados.head(5)

Aprovados: 77 alunos

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui,Qt_acertos_total,percentual_acertos,aluno_aprovado,aprovado_mat,aprovado_fis,aprovado_qui
id_aluno,,,,,,,,,,,,,
1,6,7,7,3,1,8,3,35,0.388889,True,True,True,True
2,19,10,0,0,0,11,8,48,0.533333,True,True,True,True
3,14,16,0,5,7,4,4,50,0.555556,True,True,True,True
5,7,2,2,7,0,9,3,30,0.333333,True,True,True,True
6,20,2,5,3,2,9,9,50,0.555556,True,True,True,True

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [ ]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-5ed92752-6121-474f-ab37-816918134afc.c000.csv'

In [ ]:
# 1) Sua solução aqui

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)